baseURL = 'https://footcarebyleah.github.io/footcarebyleah/'
languageCode = 'ko-kr'
title = '리아 풋케어'
theme = 'footcare-theme'

[params]
  description = '가평 문제성 발 관리 전문 - 발톱무좀, 굳은살, 각질 케어 정보'
  author = '리아 풋케어'
  email = 'footcarebyleah@gmail.com'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menu]
  [[menu.main]]
    name = '홈'
    url = '/'
    weight = 1
  
  [[menu.main]]
    name = '블로그'
    url = '/blog/'
    weight = 2
  
  [[menu.main]]
    name = '소개'
    url = '/about/'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  
  [markup.highlight]
    style = 'monokai'

[outputs]
  home = ['HTML', 'RSS', 'JSON']
  section = ['HTML', 'RSS']
